name: easy_beck
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  collection: ^1.17.1
  rxdart: ^0.27.7
  dart_mappable: ^3.1.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.1.1

flutter:
  uses-material-design: true
  assets:
   - assets/beck.json
   - fonts/
